development:
  :host: "localhost.localdomain"
  :hosts: 
  - "127.0.0.1"
  :template: "https://%s/status"

test:
  :host: "localhost.localdomain"
  :hosts: 
  - "127.0.0.1"
  :template: "https://%s/status"

production:
  :host: "status.com"
  :hosts: 
  - "10.1.2.3"
  - "10.2.3.4"
  :template: "https://%s/app/status"
